version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django
    env_file: docker/django/.env
    expose:
      - 8000
    networks:
      [ Mikhauluk ]

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks:
      [ Mikhauluk ]
    depends_on:
      - django

networks:
  Mikhauluk:
    name: Mikhauluk