version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django
    env_file: docker/django/.env
    expose:
      - 8000
    networks:
      [ Mikhauluk ]

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks:
      [ Mikhauluk ]
    depends_on:
      - django
      - frontend

  frontend:
    container_name: frontend
    image: nginx:alpine3.19-slim
    volumes:
      - ./front:/usr/share/nginx/html
    expose:
      - 80
    networks:
      [ Mikhauluk ]
networks:
  Mikhauluk:
    name: Mikhauluk